name: deploy

on:
  push:
    branches:
      - release

jobs:
  deploy:
    uses: martketplace-vkr/ci-template/.github/workflows/deploy-service.yml@release
    with:
      service_name: vendor-portal
      namespace: martketplace-vkr
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
